#!/usr/bin/env bash
# PreToolUse hook (Edit|Write matcher): blocks edits to deploy artifacts —
# build/ (any file under it, at any depth) and lambda.zip — which are
# regenerated by scripts/deploy.sh and must never be hand-edited (see the
# "Commands" section of CLAUDE.md). exit 2 blocks the tool call.
set -euo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"

if [[ -z "$file_path" ]]; then
    exit 0
fi

basename="$(basename -- "$file_path")"

# Matches build/ as a path component anywhere, not just a leading prefix —
# catches nested subdirectories too (e.g. .../build/psycopg2/_json.py).
if [[ "$file_path" == */build/* || "$file_path" == build/* ]]; then
    echo "Blocked: '$file_path' is under build/, which scripts/deploy.sh regenerates on every deploy. Edit the source in src/ instead — build/ changes are silently discarded." >&2
    exit 2
fi

if [[ "$basename" == "lambda.zip" ]]; then
    echo "Blocked: '$file_path' is a deploy artifact (lambda.zip) regenerated by scripts/deploy.sh and must not be hand-edited." >&2
    exit 2
fi

exit 0
